# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NWO-I DCC
email: nwo-i-dcc@cwi.nl
description: >- # this means to ignore newlines until "baseurl:"
  This is the NWO-I DCC Github Environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  nwo-i-dcc

# Build settings

project:
  name: NWO-I DCC Github Environment
  owner: NWO-I DCC
  repo: https://github.com/nwo-i-dcc
  version: 0.1
collections:
  workshops:
    output: true
    permalink: "/:collection/:path/"
    title: Workshops
    tab-order: 1
  tutorials:
    output: true
    permalink: "/:collection/:path/"
    title: Tutorials
    tab-order: 2
  layout_api:
    output: true
    permalink: "/:collection/:path/"
    title: Layout API
    tab-order: 3
highlighter: rouge
kramdown:
  footnote_backlink: "⮌"
permalink: pretty
sass:
  style: compressed
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
